# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\26235\Desktop\地下车库火灾预警\code\fire_alarm\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 897)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 897))
        MainWindow.setMaximumSize(QtCore.QSize(900, 897))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 390, 881, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 20, 241, 191))
        self.groupBox_21.setObjectName("groupBox_21")
        self.label_56 = QtWidgets.QLabel(self.groupBox_21)
        self.label_56.setGeometry(QtCore.QRect(20, 60, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.label_58 = QtWidgets.QLabel(self.groupBox_21)
        self.label_58.setGeometry(QtCore.QRect(20, 130, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_device1_offline = QtWidgets.QLabel(self.groupBox_21)
        self.label_device1_offline.setGeometry(QtCore.QRect(140, 110, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_offline.sizePolicy().hasHeightForWidth())
        self.label_device1_offline.setSizePolicy(sizePolicy)
        self.label_device1_offline.setStyleSheet("image: url(:/red/red.png);")
        self.label_device1_offline.setText("")
        self.label_device1_offline.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_offline.setObjectName("label_device1_offline")
        self.label_device1_online = QtWidgets.QLabel(self.groupBox_21)
        self.label_device1_online.setGeometry(QtCore.QRect(140, 40, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_online.sizePolicy().hasHeightForWidth())
        self.label_device1_online.setSizePolicy(sizePolicy)
        self.label_device1_online.setStyleSheet("image: url(:/green/green.png);")
        self.label_device1_online.setText("")
        self.label_device1_online.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_online.setObjectName("label_device1_online")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_19.setGeometry(QtCore.QRect(550, 10, 311, 401))
        self.groupBox_19.setObjectName("groupBox_19")
        self.layoutWidget_23 = QtWidgets.QWidget(self.groupBox_19)
        self.layoutWidget_23.setGeometry(QtCore.QRect(10, 30, 291, 361))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.layoutWidget_23)
        self.verticalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_42.addItem(spacerItem)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_70.addWidget(self.label_53)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.progressBar_device1_fire1 = QtWidgets.QProgressBar(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_fire1.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_fire1.setSizePolicy(sizePolicy)
        self.progressBar_device1_fire1.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device1_fire1.setProperty("value", 0)
        self.progressBar_device1_fire1.setTextVisible(False)
        self.progressBar_device1_fire1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device1_fire1.setObjectName("progressBar_device1_fire1")
        self.horizontalLayout_39.addWidget(self.progressBar_device1_fire1)
        self.label_device1_fire1 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_fire1.sizePolicy().hasHeightForWidth())
        self.label_device1_fire1.setSizePolicy(sizePolicy)
        self.label_device1_fire1.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device1_fire1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_fire1.setObjectName("label_device1_fire1")
        self.horizontalLayout_39.addWidget(self.label_device1_fire1)
        self.horizontalLayout_70.addLayout(self.horizontalLayout_39)
        self.verticalLayout_43.addLayout(self.horizontalLayout_70)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_43.addItem(spacerItem1)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_71.addWidget(self.label_54)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.progressBar_device1_fire2 = QtWidgets.QProgressBar(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_fire2.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_fire2.setSizePolicy(sizePolicy)
        self.progressBar_device1_fire2.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device1_fire2.setProperty("value", 0)
        self.progressBar_device1_fire2.setTextVisible(False)
        self.progressBar_device1_fire2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device1_fire2.setObjectName("progressBar_device1_fire2")
        self.horizontalLayout_40.addWidget(self.progressBar_device1_fire2)
        self.label_device1_fire2 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_fire2.sizePolicy().hasHeightForWidth())
        self.label_device1_fire2.setSizePolicy(sizePolicy)
        self.label_device1_fire2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device1_fire2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_fire2.setObjectName("label_device1_fire2")
        self.horizontalLayout_40.addWidget(self.label_device1_fire2)
        self.horizontalLayout_71.addLayout(self.horizontalLayout_40)
        self.verticalLayout_43.addLayout(self.horizontalLayout_71)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_43.addItem(spacerItem2)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_72.addWidget(self.label_55)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.progressBar_device1_fire3 = QtWidgets.QProgressBar(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_fire3.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_fire3.setSizePolicy(sizePolicy)
        self.progressBar_device1_fire3.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device1_fire3.setProperty("value", 0)
        self.progressBar_device1_fire3.setTextVisible(False)
        self.progressBar_device1_fire3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device1_fire3.setObjectName("progressBar_device1_fire3")
        self.horizontalLayout_41.addWidget(self.progressBar_device1_fire3)
        self.label_device1_fire3 = QtWidgets.QLabel(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_fire3.sizePolicy().hasHeightForWidth())
        self.label_device1_fire3.setSizePolicy(sizePolicy)
        self.label_device1_fire3.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device1_fire3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_fire3.setObjectName("label_device1_fire3")
        self.horizontalLayout_41.addWidget(self.label_device1_fire3)
        self.horizontalLayout_72.addLayout(self.horizontalLayout_41)
        self.verticalLayout_43.addLayout(self.horizontalLayout_72)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_43.addItem(spacerItem3)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.lineEdit_device1_fire = QtWidgets.QLineEdit(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device1_fire.sizePolicy().hasHeightForWidth())
        self.lineEdit_device1_fire.setSizePolicy(sizePolicy)
        self.lineEdit_device1_fire.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device1_fire.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device1_fire.setObjectName("lineEdit_device1_fire")
        self.horizontalLayout_24.addWidget(self.lineEdit_device1_fire)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem5)
        self.verticalLayout_43.addLayout(self.horizontalLayout_24)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_43.addItem(spacerItem6)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.verticalLayout_43.addLayout(self.horizontalLayout_73)
        self.verticalLayout_42.addLayout(self.verticalLayout_43)
        self.pushButton_device1_fire = QtWidgets.QPushButton(self.layoutWidget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device1_fire.sizePolicy().hasHeightForWidth())
        self.pushButton_device1_fire.setSizePolicy(sizePolicy)
        self.pushButton_device1_fire.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device1_fire.setObjectName("pushButton_device1_fire")
        self.verticalLayout_42.addWidget(self.pushButton_device1_fire)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_42.addItem(spacerItem7)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.verticalLayout_42.addLayout(self.horizontalLayout_74)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 220, 241, 191))
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget_3.setGeometry(QtCore.QRect(21, 21, 201, 161))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem8)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.lcdNumber_device1_temp = QtWidgets.QLCDNumber(self.layoutWidget_3)
        self.lcdNumber_device1_temp.setMinimumSize(QtCore.QSize(100, 30))
        self.lcdNumber_device1_temp.setObjectName("lcdNumber_device1_temp")
        self.horizontalLayout_45.addWidget(self.lcdNumber_device1_temp)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(30, 0))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_45.addWidget(self.label_44)
        self.verticalLayout_29.addLayout(self.horizontalLayout_45)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.lineEdit_device1_temp = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device1_temp.sizePolicy().hasHeightForWidth())
        self.lineEdit_device1_temp.setSizePolicy(sizePolicy)
        self.lineEdit_device1_temp.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device1_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device1_temp.setObjectName("lineEdit_device1_temp")
        self.horizontalLayout_7.addWidget(self.lineEdit_device1_temp)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout_29.addLayout(self.horizontalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem12)
        self.pushButton_device_temp = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device_temp.sizePolicy().hasHeightForWidth())
        self.pushButton_device_temp.setSizePolicy(sizePolicy)
        self.pushButton_device_temp.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device_temp.setObjectName("pushButton_device_temp")
        self.verticalLayout_29.addWidget(self.pushButton_device_temp)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem13)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_29.addLayout(self.horizontalLayout_46)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_18.setGeometry(QtCore.QRect(270, 20, 261, 191))
        self.groupBox_18.setObjectName("groupBox_18")
        self.layoutWidget_22 = QtWidgets.QWidget(self.groupBox_18)
        self.layoutWidget_22.setGeometry(QtCore.QRect(20, 20, 231, 161))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.layoutWidget_22)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.verticalLayout_41.addLayout(self.horizontalLayout_67)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_41.addItem(spacerItem14)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.verticalLayout_41.addLayout(self.horizontalLayout_68)
        self.verticalLayout_40.addLayout(self.verticalLayout_41)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.progressBar_device1_ir = QtWidgets.QProgressBar(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_ir.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_ir.setSizePolicy(sizePolicy)
        self.progressBar_device1_ir.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device1_ir.setProperty("value", 0)
        self.progressBar_device1_ir.setTextVisible(False)
        self.progressBar_device1_ir.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device1_ir.setObjectName("progressBar_device1_ir")
        self.horizontalLayout_22.addWidget(self.progressBar_device1_ir)
        self.label_device1_ir = QtWidgets.QLabel(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_ir.sizePolicy().hasHeightForWidth())
        self.label_device1_ir.setSizePolicy(sizePolicy)
        self.label_device1_ir.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device1_ir.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_ir.setObjectName("label_device1_ir")
        self.horizontalLayout_22.addWidget(self.label_device1_ir)
        self.verticalLayout_40.addLayout(self.horizontalLayout_22)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem15)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem16)
        self.lineEdit_device1_ir = QtWidgets.QLineEdit(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device1_ir.sizePolicy().hasHeightForWidth())
        self.lineEdit_device1_ir.setSizePolicy(sizePolicy)
        self.lineEdit_device1_ir.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device1_ir.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device1_ir.setObjectName("lineEdit_device1_ir")
        self.horizontalLayout_23.addWidget(self.lineEdit_device1_ir)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem17)
        self.verticalLayout_40.addLayout(self.horizontalLayout_23)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem18)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.pushButton_device1_ir = QtWidgets.QPushButton(self.layoutWidget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device1_ir.sizePolicy().hasHeightForWidth())
        self.pushButton_device1_ir.setSizePolicy(sizePolicy)
        self.pushButton_device1_ir.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device1_ir.setObjectName("pushButton_device1_ir")
        self.horizontalLayout_69.addWidget(self.pushButton_device1_ir)
        self.verticalLayout_40.addLayout(self.horizontalLayout_69)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem19)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_20.setGeometry(QtCore.QRect(270, 220, 261, 191))
        self.groupBox_20.setObjectName("groupBox_20")
        self.layoutWidget_24 = QtWidgets.QWidget(self.groupBox_20)
        self.layoutWidget_24.setGeometry(QtCore.QRect(20, 20, 231, 161))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.layoutWidget_24)
        self.verticalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.verticalLayout_45.addLayout(self.horizontalLayout_75)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_45.addItem(spacerItem20)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.verticalLayout_45.addLayout(self.horizontalLayout_76)
        self.verticalLayout_44.addLayout(self.verticalLayout_45)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.progressBar_device1_smoke = QtWidgets.QProgressBar(self.layoutWidget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_smoke.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_smoke.setSizePolicy(sizePolicy)
        self.progressBar_device1_smoke.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device1_smoke.setProperty("value", 0)
        self.progressBar_device1_smoke.setTextVisible(False)
        self.progressBar_device1_smoke.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device1_smoke.setObjectName("progressBar_device1_smoke")
        self.horizontalLayout_13.addWidget(self.progressBar_device1_smoke)
        self.label_device1_smoke = QtWidgets.QLabel(self.layoutWidget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_smoke.sizePolicy().hasHeightForWidth())
        self.label_device1_smoke.setSizePolicy(sizePolicy)
        self.label_device1_smoke.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device1_smoke.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_smoke.setObjectName("label_device1_smoke")
        self.horizontalLayout_13.addWidget(self.label_device1_smoke)
        self.verticalLayout_44.addLayout(self.horizontalLayout_13)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_44.addItem(spacerItem21)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem22)
        self.lineEdit_device1_smoke = QtWidgets.QLineEdit(self.layoutWidget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device1_smoke.sizePolicy().hasHeightForWidth())
        self.lineEdit_device1_smoke.setSizePolicy(sizePolicy)
        self.lineEdit_device1_smoke.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device1_smoke.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device1_smoke.setObjectName("lineEdit_device1_smoke")
        self.horizontalLayout_17.addWidget(self.lineEdit_device1_smoke)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem23)
        self.verticalLayout_44.addLayout(self.horizontalLayout_17)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_44.addItem(spacerItem24)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.pushButton_device1_smoke = QtWidgets.QPushButton(self.layoutWidget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device1_smoke.sizePolicy().hasHeightForWidth())
        self.pushButton_device1_smoke.setSizePolicy(sizePolicy)
        self.pushButton_device1_smoke.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device1_smoke.setObjectName("pushButton_device1_smoke")
        self.horizontalLayout_77.addWidget(self.pushButton_device1_smoke)
        self.verticalLayout_44.addLayout(self.horizontalLayout_77)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_44.addItem(spacerItem25)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_22.setGeometry(QtCore.QRect(550, 10, 311, 401))
        self.groupBox_22.setObjectName("groupBox_22")
        self.layoutWidget_25 = QtWidgets.QWidget(self.groupBox_22)
        self.layoutWidget_25.setGeometry(QtCore.QRect(10, 30, 291, 361))
        self.layoutWidget_25.setObjectName("layoutWidget_25")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.layoutWidget_25)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_46.addItem(spacerItem26)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_78.addWidget(self.label_59)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.progressBar_device2_fire1 = QtWidgets.QProgressBar(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_fire1.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_fire1.setSizePolicy(sizePolicy)
        self.progressBar_device2_fire1.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device2_fire1.setProperty("value", 0)
        self.progressBar_device2_fire1.setTextVisible(False)
        self.progressBar_device2_fire1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_fire1.setObjectName("progressBar_device2_fire1")
        self.horizontalLayout_42.addWidget(self.progressBar_device2_fire1)
        self.label_device2_fire1 = QtWidgets.QLabel(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_fire1.sizePolicy().hasHeightForWidth())
        self.label_device2_fire1.setSizePolicy(sizePolicy)
        self.label_device2_fire1.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device2_fire1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_fire1.setObjectName("label_device2_fire1")
        self.horizontalLayout_42.addWidget(self.label_device2_fire1)
        self.horizontalLayout_78.addLayout(self.horizontalLayout_42)
        self.verticalLayout_47.addLayout(self.horizontalLayout_78)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_47.addItem(spacerItem27)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_79.addWidget(self.label_60)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.progressBar_device2_fire2 = QtWidgets.QProgressBar(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_fire2.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_fire2.setSizePolicy(sizePolicy)
        self.progressBar_device2_fire2.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device2_fire2.setProperty("value", 0)
        self.progressBar_device2_fire2.setTextVisible(False)
        self.progressBar_device2_fire2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_fire2.setObjectName("progressBar_device2_fire2")
        self.horizontalLayout_43.addWidget(self.progressBar_device2_fire2)
        self.label_device2_fire2 = QtWidgets.QLabel(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_fire2.sizePolicy().hasHeightForWidth())
        self.label_device2_fire2.setSizePolicy(sizePolicy)
        self.label_device2_fire2.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device2_fire2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_fire2.setObjectName("label_device2_fire2")
        self.horizontalLayout_43.addWidget(self.label_device2_fire2)
        self.horizontalLayout_79.addLayout(self.horizontalLayout_43)
        self.verticalLayout_47.addLayout(self.horizontalLayout_79)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_47.addItem(spacerItem28)
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_80.addWidget(self.label_65)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.progressBar_device2_fire3 = QtWidgets.QProgressBar(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_fire3.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_fire3.setSizePolicy(sizePolicy)
        self.progressBar_device2_fire3.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device2_fire3.setProperty("value", 0)
        self.progressBar_device2_fire3.setTextVisible(False)
        self.progressBar_device2_fire3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_fire3.setObjectName("progressBar_device2_fire3")
        self.horizontalLayout_44.addWidget(self.progressBar_device2_fire3)
        self.label_device2_fire3 = QtWidgets.QLabel(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_fire3.sizePolicy().hasHeightForWidth())
        self.label_device2_fire3.setSizePolicy(sizePolicy)
        self.label_device2_fire3.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device2_fire3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_fire3.setObjectName("label_device2_fire3")
        self.horizontalLayout_44.addWidget(self.label_device2_fire3)
        self.horizontalLayout_80.addLayout(self.horizontalLayout_44)
        self.verticalLayout_47.addLayout(self.horizontalLayout_80)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_47.addItem(spacerItem29)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem30)
        self.lineEdit_device2_fire = QtWidgets.QLineEdit(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device2_fire.sizePolicy().hasHeightForWidth())
        self.lineEdit_device2_fire.setSizePolicy(sizePolicy)
        self.lineEdit_device2_fire.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device2_fire.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device2_fire.setObjectName("lineEdit_device2_fire")
        self.horizontalLayout_25.addWidget(self.lineEdit_device2_fire)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem31)
        self.verticalLayout_47.addLayout(self.horizontalLayout_25)
        spacerItem32 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_47.addItem(spacerItem32)
        self.horizontalLayout_81 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_81.setObjectName("horizontalLayout_81")
        self.verticalLayout_47.addLayout(self.horizontalLayout_81)
        self.verticalLayout_46.addLayout(self.verticalLayout_47)
        self.pushButton_device2_fire = QtWidgets.QPushButton(self.layoutWidget_25)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device2_fire.sizePolicy().hasHeightForWidth())
        self.pushButton_device2_fire.setSizePolicy(sizePolicy)
        self.pushButton_device2_fire.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device2_fire.setObjectName("pushButton_device2_fire")
        self.verticalLayout_46.addWidget(self.pushButton_device2_fire)
        spacerItem33 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_46.addItem(spacerItem33)
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.verticalLayout_46.addLayout(self.horizontalLayout_82)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 220, 241, 191))
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget_4.setGeometry(QtCore.QRect(21, 21, 201, 161))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem34)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.lcdNumber_device2_temp = QtWidgets.QLCDNumber(self.layoutWidget_4)
        self.lcdNumber_device2_temp.setMinimumSize(QtCore.QSize(100, 30))
        self.lcdNumber_device2_temp.setObjectName("lcdNumber_device2_temp")
        self.horizontalLayout_47.addWidget(self.lcdNumber_device2_temp)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setMinimumSize(QtCore.QSize(30, 0))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_47.addWidget(self.label_45)
        self.verticalLayout_30.addLayout(self.horizontalLayout_47)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem35)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem36)
        self.lineEdit_device2_temp = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device2_temp.sizePolicy().hasHeightForWidth())
        self.lineEdit_device2_temp.setSizePolicy(sizePolicy)
        self.lineEdit_device2_temp.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device2_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device2_temp.setObjectName("lineEdit_device2_temp")
        self.horizontalLayout_8.addWidget(self.lineEdit_device2_temp)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem37)
        self.verticalLayout_30.addLayout(self.horizontalLayout_8)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem38)
        self.pushButton_device2_temp = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device2_temp.sizePolicy().hasHeightForWidth())
        self.pushButton_device2_temp.setSizePolicy(sizePolicy)
        self.pushButton_device2_temp.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device2_temp.setObjectName("pushButton_device2_temp")
        self.verticalLayout_30.addWidget(self.pushButton_device2_temp)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem39)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.verticalLayout_30.addLayout(self.horizontalLayout_48)
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_23.setGeometry(QtCore.QRect(270, 20, 261, 191))
        self.groupBox_23.setObjectName("groupBox_23")
        self.layoutWidget_26 = QtWidgets.QWidget(self.groupBox_23)
        self.layoutWidget_26.setGeometry(QtCore.QRect(20, 20, 231, 161))
        self.layoutWidget_26.setObjectName("layoutWidget_26")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout(self.layoutWidget_26)
        self.verticalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.horizontalLayout_83 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_83.setObjectName("horizontalLayout_83")
        self.verticalLayout_49.addLayout(self.horizontalLayout_83)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem40)
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.verticalLayout_49.addLayout(self.horizontalLayout_84)
        self.verticalLayout_48.addLayout(self.verticalLayout_49)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.progressBar_device2_ir = QtWidgets.QProgressBar(self.layoutWidget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_ir.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_ir.setSizePolicy(sizePolicy)
        self.progressBar_device2_ir.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device2_ir.setProperty("value", 0)
        self.progressBar_device2_ir.setTextVisible(False)
        self.progressBar_device2_ir.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_ir.setObjectName("progressBar_device2_ir")
        self.horizontalLayout_26.addWidget(self.progressBar_device2_ir)
        self.label_device2_ir = QtWidgets.QLabel(self.layoutWidget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_ir.sizePolicy().hasHeightForWidth())
        self.label_device2_ir.setSizePolicy(sizePolicy)
        self.label_device2_ir.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device2_ir.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_ir.setObjectName("label_device2_ir")
        self.horizontalLayout_26.addWidget(self.label_device2_ir)
        self.verticalLayout_48.addLayout(self.horizontalLayout_26)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem41)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem42)
        self.lineEdit_device2_ir = QtWidgets.QLineEdit(self.layoutWidget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device2_ir.sizePolicy().hasHeightForWidth())
        self.lineEdit_device2_ir.setSizePolicy(sizePolicy)
        self.lineEdit_device2_ir.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device2_ir.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device2_ir.setObjectName("lineEdit_device2_ir")
        self.horizontalLayout_27.addWidget(self.lineEdit_device2_ir)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem43)
        self.verticalLayout_48.addLayout(self.horizontalLayout_27)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem44)
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.pushButton_device2_ir = QtWidgets.QPushButton(self.layoutWidget_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device2_ir.sizePolicy().hasHeightForWidth())
        self.pushButton_device2_ir.setSizePolicy(sizePolicy)
        self.pushButton_device2_ir.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device2_ir.setObjectName("pushButton_device2_ir")
        self.horizontalLayout_85.addWidget(self.pushButton_device2_ir)
        self.verticalLayout_48.addLayout(self.horizontalLayout_85)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem45)
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 20, 241, 191))
        self.groupBox_24.setObjectName("groupBox_24")
        self.label_66 = QtWidgets.QLabel(self.groupBox_24)
        self.label_66.setGeometry(QtCore.QRect(20, 60, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.groupBox_24)
        self.label_67.setGeometry(QtCore.QRect(20, 130, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_device2_offline = QtWidgets.QLabel(self.groupBox_24)
        self.label_device2_offline.setGeometry(QtCore.QRect(140, 110, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_offline.sizePolicy().hasHeightForWidth())
        self.label_device2_offline.setSizePolicy(sizePolicy)
        self.label_device2_offline.setStyleSheet("image: url(:/red/red.png);")
        self.label_device2_offline.setText("")
        self.label_device2_offline.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_offline.setObjectName("label_device2_offline")
        self.label_device2_online = QtWidgets.QLabel(self.groupBox_24)
        self.label_device2_online.setGeometry(QtCore.QRect(140, 40, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_online.sizePolicy().hasHeightForWidth())
        self.label_device2_online.setSizePolicy(sizePolicy)
        self.label_device2_online.setStyleSheet("image: url(:/green/green.png);")
        self.label_device2_online.setText("")
        self.label_device2_online.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_online.setObjectName("label_device2_online")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_25.setGeometry(QtCore.QRect(270, 220, 261, 191))
        self.groupBox_25.setObjectName("groupBox_25")
        self.layoutWidget_27 = QtWidgets.QWidget(self.groupBox_25)
        self.layoutWidget_27.setGeometry(QtCore.QRect(20, 20, 231, 161))
        self.layoutWidget_27.setObjectName("layoutWidget_27")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.layoutWidget_27)
        self.verticalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.verticalLayout_51.addLayout(self.horizontalLayout_86)
        spacerItem46 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_51.addItem(spacerItem46)
        self.horizontalLayout_87 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_87.setObjectName("horizontalLayout_87")
        self.verticalLayout_51.addLayout(self.horizontalLayout_87)
        self.verticalLayout_50.addLayout(self.verticalLayout_51)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.progressBar_device2_smoke = QtWidgets.QProgressBar(self.layoutWidget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_smoke.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_smoke.setSizePolicy(sizePolicy)
        self.progressBar_device2_smoke.setMinimumSize(QtCore.QSize(160, 0))
        self.progressBar_device2_smoke.setProperty("value", 0)
        self.progressBar_device2_smoke.setTextVisible(False)
        self.progressBar_device2_smoke.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_smoke.setObjectName("progressBar_device2_smoke")
        self.horizontalLayout_14.addWidget(self.progressBar_device2_smoke)
        self.label_device2_smoke = QtWidgets.QLabel(self.layoutWidget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_smoke.sizePolicy().hasHeightForWidth())
        self.label_device2_smoke.setSizePolicy(sizePolicy)
        self.label_device2_smoke.setMinimumSize(QtCore.QSize(10, 0))
        self.label_device2_smoke.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_smoke.setObjectName("label_device2_smoke")
        self.horizontalLayout_14.addWidget(self.label_device2_smoke)
        self.verticalLayout_50.addLayout(self.horizontalLayout_14)
        spacerItem47 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_50.addItem(spacerItem47)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem48)
        self.lineEdit_device2_smoke = QtWidgets.QLineEdit(self.layoutWidget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_device2_smoke.sizePolicy().hasHeightForWidth())
        self.lineEdit_device2_smoke.setSizePolicy(sizePolicy)
        self.lineEdit_device2_smoke.setMinimumSize(QtCore.QSize(10, 30))
        self.lineEdit_device2_smoke.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_device2_smoke.setObjectName("lineEdit_device2_smoke")
        self.horizontalLayout_18.addWidget(self.lineEdit_device2_smoke)
        spacerItem49 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem49)
        self.verticalLayout_50.addLayout(self.horizontalLayout_18)
        spacerItem50 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_50.addItem(spacerItem50)
        self.horizontalLayout_88 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_88.setObjectName("horizontalLayout_88")
        self.pushButton_device2_smoke = QtWidgets.QPushButton(self.layoutWidget_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_device2_smoke.sizePolicy().hasHeightForWidth())
        self.pushButton_device2_smoke.setSizePolicy(sizePolicy)
        self.pushButton_device2_smoke.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_device2_smoke.setObjectName("pushButton_device2_smoke")
        self.horizontalLayout_88.addWidget(self.pushButton_device2_smoke)
        self.verticalLayout_50.addLayout(self.horizontalLayout_88)
        spacerItem51 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_50.addItem(spacerItem51)
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 10, 641, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_video = QtWidgets.QLabel(self.groupBox_15)
        self.label_video.setGeometry(QtCore.QRect(0, 20, 640, 352))
        self.label_video.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setGeometry(QtCore.QRect(660, 10, 231, 381))
        self.groupBox_16.setObjectName("groupBox_16")
        self.pushButton_switch = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_switch.setGeometry(QtCore.QRect(70, 320, 93, 51))
        self.pushButton_switch.setStyleSheet("border-image: url(:/off/off.png);")
        self.pushButton_switch.setText("")
        self.pushButton_switch.setObjectName("pushButton_switch")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_ip.setGeometry(QtCore.QRect(90, 230, 131, 31))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label = QtWidgets.QLabel(self.groupBox_16)
        self.label.setGeometry(QtCore.QRect(10, 240, 54, 16))
        self.label.setObjectName("label")
        self.layoutWidget_19 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_19.setGeometry(QtCore.QRect(10, 30, 211, 186))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_35.addWidget(self.label_61)
        self.verticalLayout_2.addLayout(self.verticalLayout_35)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_57.addWidget(self.label_2)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_baudrate.sizePolicy().hasHeightForWidth())
        self.comboBox_baudrate.setSizePolicy(sizePolicy)
        self.comboBox_baudrate.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_baudrate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.horizontalLayout_57.addWidget(self.comboBox_baudrate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_58.addWidget(self.label_62)
        self.comboBox_stopBit = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_stopBit.sizePolicy().hasHeightForWidth())
        self.comboBox_stopBit.setSizePolicy(sizePolicy)
        self.comboBox_stopBit.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_stopBit.setObjectName("comboBox_stopBit")
        self.horizontalLayout_58.addWidget(self.comboBox_stopBit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_59.addWidget(self.label_63)
        self.comboBox_dataBit = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_dataBit.sizePolicy().hasHeightForWidth())
        self.comboBox_dataBit.setSizePolicy(sizePolicy)
        self.comboBox_dataBit.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_dataBit.setObjectName("comboBox_dataBit")
        self.horizontalLayout_59.addWidget(self.comboBox_dataBit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_60.addWidget(self.label_64)
        self.comboBox_parity = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_parity.sizePolicy().hasHeightForWidth())
        self.comboBox_parity.setSizePolicy(sizePolicy)
        self.comboBox_parity.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.horizontalLayout_60.addWidget(self.comboBox_parity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_60)
        self.lineEdit_telephone = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_telephone.setGeometry(QtCore.QRect(90, 270, 131, 31))
        self.lineEdit_telephone.setObjectName("lineEdit_telephone")
        self.label_57 = QtWidgets.QLabel(self.groupBox_16)
        self.label_57.setGeometry(QtCore.QRect(10, 280, 81, 16))
        self.label_57.setObjectName("label_57")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_21.setTitle(_translate("MainWindow", "在线状态"))
        self.label_56.setText(_translate("MainWindow", "在线："))
        self.label_58.setText(_translate("MainWindow", "离线："))
        self.groupBox_19.setTitle(_translate("MainWindow", "火焰检测"))
        self.label_53.setText(_translate("MainWindow", "火焰1："))
        self.progressBar_device1_fire1.setFormat(_translate("MainWindow", "%p%"))
        self.label_device1_fire1.setText(_translate("MainWindow", "0"))
        self.label_54.setText(_translate("MainWindow", "火焰2："))
        self.progressBar_device1_fire2.setFormat(_translate("MainWindow", "%p%"))
        self.label_device1_fire2.setText(_translate("MainWindow", "0"))
        self.label_55.setText(_translate("MainWindow", "火焰3："))
        self.progressBar_device1_fire3.setFormat(_translate("MainWindow", "%p%"))
        self.label_device1_fire3.setText(_translate("MainWindow", "0"))
        self.lineEdit_device1_fire.setText(_translate("MainWindow", "1.0"))
        self.pushButton_device1_fire.setText(_translate("MainWindow", "设定报警值"))
        self.groupBox_11.setTitle(_translate("MainWindow", "温度检测"))
        self.label_44.setText(_translate("MainWindow", "℃"))
        self.lineEdit_device1_temp.setText(_translate("MainWindow", "30"))
        self.pushButton_device_temp.setText(_translate("MainWindow", "设定报警值"))
        self.groupBox_18.setTitle(_translate("MainWindow", "热成像检测"))
        self.progressBar_device1_ir.setFormat(_translate("MainWindow", "%p%"))
        self.label_device1_ir.setText(_translate("MainWindow", "0"))
        self.lineEdit_device1_ir.setText(_translate("MainWindow", "30"))
        self.pushButton_device1_ir.setText(_translate("MainWindow", "设定报警值"))
        self.groupBox_20.setTitle(_translate("MainWindow", "烟雾检测"))
        self.progressBar_device1_smoke.setFormat(_translate("MainWindow", "%p%"))
        self.label_device1_smoke.setText(_translate("MainWindow", "0"))
        self.lineEdit_device1_smoke.setText(_translate("MainWindow", "1.0"))
        self.pushButton_device1_smoke.setText(_translate("MainWindow", "设定报警值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1号停车位"))
        self.groupBox_22.setTitle(_translate("MainWindow", "火焰检测"))
        self.label_59.setText(_translate("MainWindow", "火焰1："))
        self.progressBar_device2_fire1.setFormat(_translate("MainWindow", "%p%"))
        self.label_device2_fire1.setText(_translate("MainWindow", "0"))
        self.label_60.setText(_translate("MainWindow", "火焰2："))
        self.progressBar_device2_fire2.setFormat(_translate("MainWindow", "%p%"))
        self.label_device2_fire2.setText(_translate("MainWindow", "0"))
        self.label_65.setText(_translate("MainWindow", "火焰3："))
        self.progressBar_device2_fire3.setFormat(_translate("MainWindow", "%p%"))
        self.label_device2_fire3.setText(_translate("MainWindow", "0"))
        self.lineEdit_device2_fire.setText(_translate("MainWindow", "1.0"))
        self.pushButton_device2_fire.setText(_translate("MainWindow", "设定报警值"))
        self.groupBox_12.setTitle(_translate("MainWindow", "温度检测"))
        self.label_45.setText(_translate("MainWindow", "℃"))
        self.lineEdit_device2_temp.setText(_translate("MainWindow", "30"))
        self.pushButton_device2_temp.setText(_translate("MainWindow", "设定报警值"))
        self.groupBox_23.setTitle(_translate("MainWindow", "热成像检测"))
        self.progressBar_device2_ir.setFormat(_translate("MainWindow", "%p%"))
        self.label_device2_ir.setText(_translate("MainWindow", "0"))
        self.lineEdit_device2_ir.setText(_translate("MainWindow", "30"))
        self.pushButton_device2_ir.setText(_translate("MainWindow", "设定报警值"))
        self.groupBox_24.setTitle(_translate("MainWindow", "在线状态"))
        self.label_66.setText(_translate("MainWindow", "在线："))
        self.label_67.setText(_translate("MainWindow", "离线："))
        self.groupBox_25.setTitle(_translate("MainWindow", "烟雾检测"))
        self.progressBar_device2_smoke.setFormat(_translate("MainWindow", "%p%"))
        self.label_device2_smoke.setText(_translate("MainWindow", "0"))
        self.lineEdit_device2_smoke.setText(_translate("MainWindow", "1.0"))
        self.pushButton_device2_smoke.setText(_translate("MainWindow", "设定报警值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2号停车位"))
        self.groupBox_15.setTitle(_translate("MainWindow", "视频显示"))
        self.groupBox_16.setTitle(_translate("MainWindow", "配置"))
        self.lineEdit_ip.setText(_translate("MainWindow", "192.168.1.103"))
        self.label.setText(_translate("MainWindow", "IP地址:"))
        self.label_61.setText(_translate("MainWindow", "串口："))
        self.label_2.setText(_translate("MainWindow", "波特率："))
        self.label_62.setText(_translate("MainWindow", "停止位："))
        self.label_63.setText(_translate("MainWindow", "数据位："))
        self.label_64.setText(_translate("MainWindow", "奇偶校验："))
        self.lineEdit_telephone.setText(_translate("MainWindow", "19821213221"))
        self.label_57.setText(_translate("MainWindow", "报警电话："))

import resource_rc
