# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\26235\Desktop\地下车库火灾预警\code\fire_alarm\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 897)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 897))
        MainWindow.setMaximumSize(QtCore.QSize(900, 897))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 400, 851, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 241, 191))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 20, 213, 162))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lcdNumber_temp = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber_temp.setMinimumSize(QtCore.QSize(100, 0))
        self.lcdNumber_temp.setObjectName("lcdNumber_temp")
        self.horizontalLayout.addWidget(self.lcdNumber_temp)
        self.label_17 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(30, 0))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.dial_device1_temp1 = QtWidgets.QDial(self.widget)
        self.dial_device1_temp1.setWrapping(False)
        self.dial_device1_temp1.setObjectName("dial_device1_temp1")
        self.horizontalLayout_8.addWidget(self.dial_device1_temp1)
        self.dial_device1_temp2 = QtWidgets.QDial(self.widget)
        self.dial_device1_temp2.setObjectName("dial_device1_temp2")
        self.horizontalLayout_8.addWidget(self.dial_device1_temp2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 10, 241, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(20, 20, 213, 171))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.progressBar_device1_smoke = QtWidgets.QProgressBar(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_smoke.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_smoke.setSizePolicy(sizePolicy)
        self.progressBar_device1_smoke.setMinimumSize(QtCore.QSize(100, 10))
        self.progressBar_device1_smoke.setProperty("value", 24)
        self.progressBar_device1_smoke.setTextVisible(False)
        self.progressBar_device1_smoke.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device1_smoke.setObjectName("progressBar_device1_smoke")
        self.verticalLayout_10.addWidget(self.progressBar_device1_smoke)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.dial_device1_ir1 = QtWidgets.QDial(self.layoutWidget_7)
        self.dial_device1_ir1.setObjectName("dial_device1_ir1")
        self.horizontalLayout_19.addWidget(self.dial_device1_ir1)
        self.dial_device1_ir2 = QtWidgets.QDial(self.layoutWidget_7)
        self.dial_device1_ir2.setObjectName("dial_device1_ir2")
        self.horizontalLayout_19.addWidget(self.dial_device1_ir2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(530, 10, 301, 401))
        self.groupBox_4.setObjectName("groupBox_4")
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(20, 30, 266, 361))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.progressBar_device1_fire1 = QtWidgets.QProgressBar(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_fire1.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_fire1.setSizePolicy(sizePolicy)
        self.progressBar_device1_fire1.setMinimumSize(QtCore.QSize(200, 10))
        self.progressBar_device1_fire1.setMaximum(100)
        self.progressBar_device1_fire1.setProperty("value", 24)
        self.progressBar_device1_fire1.setTextVisible(False)
        self.progressBar_device1_fire1.setObjectName("progressBar_device1_fire1")
        self.horizontalLayout_3.addWidget(self.progressBar_device1_fire1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.progressBar_device1_fire2 = QtWidgets.QProgressBar(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_fire2.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_fire2.setSizePolicy(sizePolicy)
        self.progressBar_device1_fire2.setMinimumSize(QtCore.QSize(200, 10))
        self.progressBar_device1_fire2.setProperty("value", 24)
        self.progressBar_device1_fire2.setTextVisible(False)
        self.progressBar_device1_fire2.setObjectName("progressBar_device1_fire2")
        self.horizontalLayout_4.addWidget(self.progressBar_device1_fire2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.progressBar_device1_fire3 = QtWidgets.QProgressBar(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device1_fire3.sizePolicy().hasHeightForWidth())
        self.progressBar_device1_fire3.setSizePolicy(sizePolicy)
        self.progressBar_device1_fire3.setMinimumSize(QtCore.QSize(200, 10))
        self.progressBar_device1_fire3.setProperty("value", 24)
        self.progressBar_device1_fire3.setTextVisible(False)
        self.progressBar_device1_fire3.setObjectName("progressBar_device1_fire3")
        self.horizontalLayout_5.addWidget(self.progressBar_device1_fire3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dial_device1_fire1 = QtWidgets.QDial(self.widget1)
        self.dial_device1_fire1.setObjectName("dial_device1_fire1")
        self.horizontalLayout_9.addWidget(self.dial_device1_fire1)
        self.dial_device1_fire2 = QtWidgets.QDial(self.widget1)
        self.dial_device1_fire2.setObjectName("dial_device1_fire2")
        self.horizontalLayout_9.addWidget(self.dial_device1_fire2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 15))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 220, 241, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(20, 20, 213, 161))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.progressBar_smoke = QtWidgets.QProgressBar(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_smoke.sizePolicy().hasHeightForWidth())
        self.progressBar_smoke.setSizePolicy(sizePolicy)
        self.progressBar_smoke.setMinimumSize(QtCore.QSize(100, 0))
        self.progressBar_smoke.setProperty("value", 24)
        self.progressBar_smoke.setTextVisible(False)
        self.progressBar_smoke.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_smoke.setObjectName("progressBar_smoke")
        self.verticalLayout_8.addWidget(self.progressBar_smoke)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.dial_device1_smoke1 = QtWidgets.QDial(self.layoutWidget_4)
        self.dial_device1_smoke1.setObjectName("dial_device1_smoke1")
        self.horizontalLayout_16.addWidget(self.dial_device1_smoke1)
        self.dial_device1_smoke2 = QtWidgets.QDial(self.layoutWidget_4)
        self.dial_device1_smoke2.setObjectName("dial_device1_smoke2")
        self.horizontalLayout_16.addWidget(self.dial_device1_smoke2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 20, 241, 191))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_27 = QtWidgets.QLabel(self.groupBox_9)
        self.label_27.setGeometry(QtCore.QRect(20, 60, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        self.label_28.setGeometry(QtCore.QRect(20, 130, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_device1_online = QtWidgets.QLabel(self.groupBox_9)
        self.label_device1_online.setGeometry(QtCore.QRect(140, 40, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_online.sizePolicy().hasHeightForWidth())
        self.label_device1_online.setSizePolicy(sizePolicy)
        self.label_device1_online.setStyleSheet("image: url(:/green/green.png);")
        self.label_device1_online.setText("")
        self.label_device1_online.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_online.setObjectName("label_device1_online")
        self.label_device1_offline = QtWidgets.QLabel(self.groupBox_9)
        self.label_device1_offline.setGeometry(QtCore.QRect(140, 110, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device1_offline.sizePolicy().hasHeightForWidth())
        self.label_device1_offline.setSizePolicy(sizePolicy)
        self.label_device1_offline.setStyleSheet("image: url(:/red/red.png);")
        self.label_device1_offline.setText("")
        self.label_device1_offline.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device1_offline.setObjectName("label_device1_offline")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 220, 241, 191))
        self.groupBox_10.setObjectName("groupBox_10")
        self.layoutWidget_15 = QtWidgets.QWidget(self.groupBox_10)
        self.layoutWidget_15.setGeometry(QtCore.QRect(20, 20, 213, 162))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.lcdNumber_device2_temp = QtWidgets.QLCDNumber(self.layoutWidget_15)
        self.lcdNumber_device2_temp.setMinimumSize(QtCore.QSize(100, 0))
        self.lcdNumber_device2_temp.setObjectName("lcdNumber_device2_temp")
        self.horizontalLayout_43.addWidget(self.lcdNumber_device2_temp)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setMinimumSize(QtCore.QSize(30, 0))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_43.addWidget(self.label_43)
        self.verticalLayout_28.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.dial_device2_temp1 = QtWidgets.QDial(self.layoutWidget_15)
        self.dial_device2_temp1.setWrapping(False)
        self.dial_device2_temp1.setObjectName("dial_device2_temp1")
        self.horizontalLayout_44.addWidget(self.dial_device2_temp1)
        self.dial_device2_temp2 = QtWidgets.QDial(self.layoutWidget_15)
        self.dial_device2_temp2.setObjectName("dial_device2_temp2")
        self.horizontalLayout_44.addWidget(self.dial_device2_temp2)
        self.verticalLayout_28.addLayout(self.horizontalLayout_44)
        self.verticalLayout_27.addLayout(self.verticalLayout_28)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_45.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_45.addWidget(self.label_45)
        self.verticalLayout_27.addLayout(self.horizontalLayout_45)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(270, 10, 241, 201))
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget_16 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget_16.setGeometry(QtCore.QRect(20, 20, 213, 171))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.layoutWidget_16)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_30.addLayout(self.horizontalLayout_46)
        self.progressBar_device2_ir = QtWidgets.QProgressBar(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_ir.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_ir.setSizePolicy(sizePolicy)
        self.progressBar_device2_ir.setMinimumSize(QtCore.QSize(100, 10))
        self.progressBar_device2_ir.setProperty("value", 24)
        self.progressBar_device2_ir.setTextVisible(False)
        self.progressBar_device2_ir.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_ir.setObjectName("progressBar_device2_ir")
        self.verticalLayout_30.addWidget(self.progressBar_device2_ir)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.dial_device2_ir1 = QtWidgets.QDial(self.layoutWidget_16)
        self.dial_device2_ir1.setObjectName("dial_device2_ir1")
        self.horizontalLayout_47.addWidget(self.dial_device2_ir1)
        self.dial_device2_ir2 = QtWidgets.QDial(self.layoutWidget_16)
        self.dial_device2_ir2.setObjectName("dial_device2_ir2")
        self.horizontalLayout_47.addWidget(self.dial_device2_ir2)
        self.verticalLayout_30.addLayout(self.horizontalLayout_47)
        self.verticalLayout_29.addLayout(self.verticalLayout_30)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_48.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_48.addWidget(self.label_47)
        self.verticalLayout_29.addLayout(self.horizontalLayout_48)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 20, 241, 191))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_48 = QtWidgets.QLabel(self.groupBox_12)
        self.label_48.setGeometry(QtCore.QRect(20, 60, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_12)
        self.label_49.setGeometry(QtCore.QRect(20, 130, 101, 15))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.label_device2_offline = QtWidgets.QLabel(self.groupBox_12)
        self.label_device2_offline.setGeometry(QtCore.QRect(140, 110, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_offline.sizePolicy().hasHeightForWidth())
        self.label_device2_offline.setSizePolicy(sizePolicy)
        self.label_device2_offline.setStyleSheet("image: url(:/red/red.png);")
        self.label_device2_offline.setText("")
        self.label_device2_offline.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_offline.setObjectName("label_device2_offline")
        self.label_device2_online = QtWidgets.QLabel(self.groupBox_12)
        self.label_device2_online.setGeometry(QtCore.QRect(140, 40, 71, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_device2_online.sizePolicy().hasHeightForWidth())
        self.label_device2_online.setSizePolicy(sizePolicy)
        self.label_device2_online.setStyleSheet("image: url(:/green/green.png);")
        self.label_device2_online.setText("")
        self.label_device2_online.setAlignment(QtCore.Qt.AlignCenter)
        self.label_device2_online.setObjectName("label_device2_online")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_13.setGeometry(QtCore.QRect(530, 10, 301, 401))
        self.groupBox_13.setObjectName("groupBox_13")
        self.layoutWidget_17 = QtWidgets.QWidget(self.groupBox_13)
        self.layoutWidget_17.setGeometry(QtCore.QRect(20, 30, 266, 361))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.layoutWidget_17)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_49.addWidget(self.label_50)
        self.progressBar_device2_fire1 = QtWidgets.QProgressBar(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_fire1.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_fire1.setSizePolicy(sizePolicy)
        self.progressBar_device2_fire1.setMinimumSize(QtCore.QSize(200, 10))
        self.progressBar_device2_fire1.setMaximum(100)
        self.progressBar_device2_fire1.setProperty("value", 24)
        self.progressBar_device2_fire1.setTextVisible(False)
        self.progressBar_device2_fire1.setObjectName("progressBar_device2_fire1")
        self.horizontalLayout_49.addWidget(self.progressBar_device2_fire1)
        self.verticalLayout_32.addLayout(self.horizontalLayout_49)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem3)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_50.addWidget(self.label_51)
        self.progressBar_device2_fire2 = QtWidgets.QProgressBar(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_fire2.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_fire2.setSizePolicy(sizePolicy)
        self.progressBar_device2_fire2.setMinimumSize(QtCore.QSize(200, 10))
        self.progressBar_device2_fire2.setProperty("value", 24)
        self.progressBar_device2_fire2.setTextVisible(False)
        self.progressBar_device2_fire2.setObjectName("progressBar_device2_fire2")
        self.horizontalLayout_50.addWidget(self.progressBar_device2_fire2)
        self.verticalLayout_32.addLayout(self.horizontalLayout_50)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem4)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_51.addWidget(self.label_52)
        self.progressBar_device2_fire3 = QtWidgets.QProgressBar(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_fire3.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_fire3.setSizePolicy(sizePolicy)
        self.progressBar_device2_fire3.setMinimumSize(QtCore.QSize(200, 10))
        self.progressBar_device2_fire3.setProperty("value", 24)
        self.progressBar_device2_fire3.setTextVisible(False)
        self.progressBar_device2_fire3.setObjectName("progressBar_device2_fire3")
        self.horizontalLayout_51.addWidget(self.progressBar_device2_fire3)
        self.verticalLayout_32.addLayout(self.horizontalLayout_51)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_32.addItem(spacerItem5)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.dial_device2_fire1 = QtWidgets.QDial(self.layoutWidget_17)
        self.dial_device2_fire1.setObjectName("dial_device2_fire1")
        self.horizontalLayout_52.addWidget(self.dial_device2_fire1)
        self.dial_device2_fire2 = QtWidgets.QDial(self.layoutWidget_17)
        self.dial_device2_fire2.setObjectName("dial_device2_fire2")
        self.horizontalLayout_52.addWidget(self.dial_device2_fire2)
        self.verticalLayout_32.addLayout(self.horizontalLayout_52)
        self.verticalLayout_31.addLayout(self.verticalLayout_32)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_53.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setMinimumSize(QtCore.QSize(0, 15))
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_53.addWidget(self.label_54)
        self.verticalLayout_31.addLayout(self.horizontalLayout_53)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setGeometry(QtCore.QRect(270, 220, 241, 191))
        self.groupBox_14.setObjectName("groupBox_14")
        self.layoutWidget_18 = QtWidgets.QWidget(self.groupBox_14)
        self.layoutWidget_18.setGeometry(QtCore.QRect(20, 20, 213, 161))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.layoutWidget_18)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.verticalLayout_34.addLayout(self.horizontalLayout_54)
        self.progressBar_device2_smoke = QtWidgets.QProgressBar(self.layoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_device2_smoke.sizePolicy().hasHeightForWidth())
        self.progressBar_device2_smoke.setSizePolicy(sizePolicy)
        self.progressBar_device2_smoke.setMinimumSize(QtCore.QSize(100, 0))
        self.progressBar_device2_smoke.setProperty("value", 24)
        self.progressBar_device2_smoke.setTextVisible(False)
        self.progressBar_device2_smoke.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_device2_smoke.setObjectName("progressBar_device2_smoke")
        self.verticalLayout_34.addWidget(self.progressBar_device2_smoke)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.dial_device2_smoke1 = QtWidgets.QDial(self.layoutWidget_18)
        self.dial_device2_smoke1.setObjectName("dial_device2_smoke1")
        self.horizontalLayout_55.addWidget(self.dial_device2_smoke1)
        self.dial_device2_smoke2 = QtWidgets.QDial(self.layoutWidget_18)
        self.dial_device2_smoke2.setObjectName("dial_device2_smoke2")
        self.horizontalLayout_55.addWidget(self.dial_device2_smoke2)
        self.verticalLayout_34.addLayout(self.horizontalLayout_55)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_56.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_56.addWidget(self.label_56)
        self.verticalLayout_33.addLayout(self.horizontalLayout_56)
        self.tabWidget.addTab(self.tab_2, "")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 10, 641, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_video = QtWidgets.QLabel(self.groupBox_15)
        self.label_video.setGeometry(QtCore.QRect(0, 20, 640, 352))
        self.label_video.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_16.setGeometry(QtCore.QRect(660, 10, 231, 381))
        self.groupBox_16.setObjectName("groupBox_16")
        self.pushButton_switch = QtWidgets.QPushButton(self.groupBox_16)
        self.pushButton_switch.setGeometry(QtCore.QRect(70, 320, 93, 51))
        self.pushButton_switch.setStyleSheet("border-image: url(:/off/off.png);")
        self.pushButton_switch.setText("")
        self.pushButton_switch.setObjectName("pushButton_switch")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_ip.setGeometry(QtCore.QRect(90, 230, 131, 31))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label = QtWidgets.QLabel(self.groupBox_16)
        self.label.setGeometry(QtCore.QRect(10, 240, 54, 16))
        self.label.setObjectName("label")
        self.layoutWidget_19 = QtWidgets.QWidget(self.groupBox_16)
        self.layoutWidget_19.setGeometry(QtCore.QRect(10, 30, 211, 186))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_61 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_35.addWidget(self.label_61)
        self.verticalLayout_2.addLayout(self.verticalLayout_35)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_57.addWidget(self.label_2)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_baudrate.sizePolicy().hasHeightForWidth())
        self.comboBox_baudrate.setSizePolicy(sizePolicy)
        self.comboBox_baudrate.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_baudrate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.horizontalLayout_57.addWidget(self.comboBox_baudrate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_58.addWidget(self.label_62)
        self.comboBox_stopBit = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_stopBit.sizePolicy().hasHeightForWidth())
        self.comboBox_stopBit.setSizePolicy(sizePolicy)
        self.comboBox_stopBit.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_stopBit.setObjectName("comboBox_stopBit")
        self.horizontalLayout_58.addWidget(self.comboBox_stopBit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_63 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_59.addWidget(self.label_63)
        self.comboBox_dataBit = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_dataBit.sizePolicy().hasHeightForWidth())
        self.comboBox_dataBit.setSizePolicy(sizePolicy)
        self.comboBox_dataBit.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_dataBit.setObjectName("comboBox_dataBit")
        self.horizontalLayout_59.addWidget(self.comboBox_dataBit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_64.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_60.addWidget(self.label_64)
        self.comboBox_parity = QtWidgets.QComboBox(self.layoutWidget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_parity.sizePolicy().hasHeightForWidth())
        self.comboBox_parity.setSizePolicy(sizePolicy)
        self.comboBox_parity.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.horizontalLayout_60.addWidget(self.comboBox_parity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_60)
        self.lineEdit_telephone = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_telephone.setGeometry(QtCore.QRect(90, 270, 131, 31))
        self.lineEdit_telephone.setObjectName("lineEdit_telephone")
        self.label_57 = QtWidgets.QLabel(self.groupBox_16)
        self.label_57.setGeometry(QtCore.QRect(10, 280, 81, 16))
        self.label_57.setObjectName("label_57")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "温度检测"))
        self.label_17.setText(_translate("MainWindow", "℃"))
        self.label_11.setText(_translate("MainWindow", "报警值"))
        self.label_12.setText(_translate("MainWindow", "最大值"))
        self.groupBox_3.setTitle(_translate("MainWindow", "热成像检测"))
        self.progressBar_device1_smoke.setFormat(_translate("MainWindow", "%p%"))
        self.label_15.setText(_translate("MainWindow", "报警值"))
        self.label_16.setText(_translate("MainWindow", "最大值"))
        self.groupBox_4.setTitle(_translate("MainWindow", "火焰检测"))
        self.label_3.setText(_translate("MainWindow", "火焰1："))
        self.progressBar_device1_fire1.setFormat(_translate("MainWindow", "%p%"))
        self.label_4.setText(_translate("MainWindow", "火焰2："))
        self.progressBar_device1_fire2.setFormat(_translate("MainWindow", "%p%"))
        self.label_5.setText(_translate("MainWindow", "火焰3："))
        self.progressBar_device1_fire3.setFormat(_translate("MainWindow", "%p%"))
        self.label_9.setText(_translate("MainWindow", "报警值"))
        self.label_10.setText(_translate("MainWindow", "最大值"))
        self.groupBox_2.setTitle(_translate("MainWindow", "烟雾检测"))
        self.progressBar_smoke.setFormat(_translate("MainWindow", "%p%"))
        self.label_13.setText(_translate("MainWindow", "报警值"))
        self.label_14.setText(_translate("MainWindow", "最大值"))
        self.groupBox_9.setTitle(_translate("MainWindow", "在线状态"))
        self.label_27.setText(_translate("MainWindow", "在线："))
        self.label_28.setText(_translate("MainWindow", "离线："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "1号停车位"))
        self.groupBox_10.setTitle(_translate("MainWindow", "温度检测"))
        self.label_43.setText(_translate("MainWindow", "℃"))
        self.label_44.setText(_translate("MainWindow", "报警值"))
        self.label_45.setText(_translate("MainWindow", "最大值"))
        self.groupBox_11.setTitle(_translate("MainWindow", "热成像检测"))
        self.progressBar_device2_ir.setFormat(_translate("MainWindow", "%p%"))
        self.label_46.setText(_translate("MainWindow", "报警值"))
        self.label_47.setText(_translate("MainWindow", "最大值"))
        self.groupBox_12.setTitle(_translate("MainWindow", "在线状态"))
        self.label_48.setText(_translate("MainWindow", "在线："))
        self.label_49.setText(_translate("MainWindow", "离线："))
        self.groupBox_13.setTitle(_translate("MainWindow", "火焰检测"))
        self.label_50.setText(_translate("MainWindow", "火焰1："))
        self.progressBar_device2_fire1.setFormat(_translate("MainWindow", "%p%"))
        self.label_51.setText(_translate("MainWindow", "火焰2："))
        self.progressBar_device2_fire2.setFormat(_translate("MainWindow", "%p%"))
        self.label_52.setText(_translate("MainWindow", "火焰3："))
        self.progressBar_device2_fire3.setFormat(_translate("MainWindow", "%p%"))
        self.label_53.setText(_translate("MainWindow", "报警值"))
        self.label_54.setText(_translate("MainWindow", "最大值"))
        self.groupBox_14.setTitle(_translate("MainWindow", "烟雾检测"))
        self.progressBar_device2_smoke.setFormat(_translate("MainWindow", "%p%"))
        self.label_55.setText(_translate("MainWindow", "报警值"))
        self.label_56.setText(_translate("MainWindow", "最大值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "2号停车位"))
        self.groupBox_15.setTitle(_translate("MainWindow", "视频显示"))
        self.groupBox_16.setTitle(_translate("MainWindow", "配置"))
        self.lineEdit_ip.setText(_translate("MainWindow", "192.168.1.103"))
        self.label.setText(_translate("MainWindow", "IP地址:"))
        self.label_61.setText(_translate("MainWindow", "串口："))
        self.label_2.setText(_translate("MainWindow", "波特率："))
        self.label_62.setText(_translate("MainWindow", "停止位："))
        self.label_63.setText(_translate("MainWindow", "数据位："))
        self.label_64.setText(_translate("MainWindow", "奇偶校验："))
        self.lineEdit_telephone.setText(_translate("MainWindow", "19821213221"))
        self.label_57.setText(_translate("MainWindow", "报警电话："))

import resource_rc
